---
- name: Playbook to bootstrap a Rasberry with HypriotOS
  gather_facts: no
  hosts: hypriot
  vars_files:
    - secrets.yml
  tasks:
  - name: Copy SSH key to first-time booted Hypriot OS on Raspberry Pi
    authorized_key:
      user: pirate
      state: present
      key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

  - name: Set Hostname
    hostname:
      name: "{{ inventory_hostname }}"

  - name: Update packages
    apt: 
      upgrade: dist

  - name: Change pirate password
    user:
      name: pirate
      password: "{{ pirate_password }}"
